version: "3"

services:

  api:
    build: .
    container_name: api
    restart: always
    env_file: 
        - .env
    environment:
        - NODE_ENV=development
    volumes:
        - .:/usr/src/app
    depends_on: 
        - mysqldb
    links:
        - mysqldb
    ports: 
      - ${APP_PORT}:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: npm run start

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    #platform: linux/x86_64
    restart: always
    command: --innodb-use-native-aio=0
    env_file: 
        - .env
    ports: 
        - ${DB_PORT}:3306
    tty: true
    volumes: 
      - dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      #- MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
    dbdata: